### ISSUE TITLE
Linux无法安装ntchat(linux Ubantu Python3.10.9 pip install ntchat）

### ISSUE THREAD

**Issue by a3311598** [haikerapples/timetask#14]
chatgpt-on-wechat : 部署方式railway

**Comment by fatwang2** [comment]
请问这个问题最后是怎么解决的？

**Comment by a3311598** [comment]
没有解决，发现这个项目chatgpt-on-wechat好像没用到，所以直接删了，不然部署不了。其它的发现有个时区问题，这个可能要预先配置服务器时区。有一个优化的地方感觉可以改进一下，就是回复的时候可以带上前缀区分一下真人，比如GPT 夸夸我。

**Comment by a3311598** [comment]
目前项目可以正常使用，不过railway后台一直在打日志。不知道咋调。

**Comment by a3311598** [comment]
还有一个设置十点十分任务可以生效，设置10:10 就无法生效了。

**Comment by fatwang2** [comment]
> 没有解决，发现这个项目chatgpt-on-wechat好像没用到，所以直接删了，不然部署不了。其它的发现有个时区问题，这个可能要预先配置服务器时区。有一个优化的地方感觉可以改进一下，就是回复的时候可以带上前缀区分一下真人，比如GPT 夸夸我。

时区问题是说是以服务器的时区为准来做推送提醒的吗？

**Comment by fatwang2** [comment]
> 目前项目可以正常使用，不过railway后台一直在打日志。不知道咋调。

一直打日志什么意思？我之前也用railway部署过，deploy log 一直显示不是正常的吗？

**Comment by fatwang2** [comment]
> 还有一个设置十点十分任务可以生效，设置10:10 就无法生效了。就是没有在任务列表里面

我的 10:10 也可以，任务添加成功，只是一直没有收到提醒

**Comment by a3311598** [comment]
> > 没有解决，发现这个项目chatgpt-on-wechat好像没用到，所以直接删了，不然部署不了。其它的发现有个时区问题，这个可能要预先配置服务器时区。有一个优化的地方感觉可以改进一下，就是回复的时候可以带上前缀区分一下真人，比如GPT 夸夸我。
> 
> 时区问题是说是以服务器的时区为准来做推送提醒的吗？

对，它是以服务器的时区为准来做推送提醒的，所以我每次设置要往前推8个时区

**Comment by a3311598** [comment]
> 10:10
我这边也是可以添加成功，不过不在任务列表里面，也没生效

**Comment by a3311598** [comment]
> > 目前项目可以正常使用，不过railway后台一直在打日志。不知道咋调。
> 
> 一直打日志什么意思？我之前也用railway部署过，deploy log 一直显示不是正常的吗？

这应该不是问题，但是我要看后台消息就不好看了，一直cycle会覆盖掉其他消息

**Comment by a3311598** [comment]
> 



> > > 目前项目可以正常使用，不过railway后台一直在打日志。不知道咋调。
> > 
> > 
> > 一直打日志什么意思？我之前也用railway部署过，deploy log 一直显示不是正常的吗？
> 
> 这应该不是问题，但是我要看后台消息就不好看了，一直cycle会覆盖掉其他消息

要是能在触发的时候再打日志就好了，不知道是否可行

**Comment by a3311598** [comment]
> > 还有一个设置十点十分任务可以生效，设置10:10 就无法生效了。就是没有在任务列表里面
> 
> 我的 10:10 也可以，任务添加成功，只是一直没有收到提醒

10:10我这边也是可以添加成功，不过不在任务列表里面，也没生效

**Comment by a3311598** [comment]
> > > 目前项目可以正常使用，不过railway后台一直在打日志。不知道咋调。
> > 
> > 
> > 一直打日志什么意思？我之前也用railway部署过，deploy log 一直显示不是正常的吗？
> 
> 这应该不是问题，但是我要看后台消息就不好看了，一直cycl

**Comment by haikerapples** [comment]
timatask 的依赖库 requirements.txt文件，已默认移除了ntchat；后续无需主动移除了

**Comment by fatwang2** [comment]
> > > 没有解决，发现这个项目chatgpt-on-wechat好像没用到，所以直接删了，不然部署不了。其它的发现有个时区问题，这个可能要预先配置服务器时区。有一个优化的地方感觉可以改进一下，就是回复的时候可以带上前缀区分一下真人，比如GPT 夸夸我。
> > 
> > 
> > 时区问题是说是以服务器的时区为准来做推送提醒的吗？
> 
> 对，它是以服务器的时区为准来做推送提醒的，所以我每次设置要往前推8个时区

这个直接在命令行里改下服务器的时区就行，我自己试了下可以解决

**Comment by fatwang2** [comment]
> > > 还有一个设置十点十分任务可以生效，设置10:10 就无法生效了。就是没有在任务列表里面
> > 
> > 
> > 我的 10:10 也可以，任务添加成功，只是一直没有收到提醒
> 
> 10:10我这边也是可以添加成功，不过不在任务列表里面，也没生效

我现在是可以添加成功，且在任务列表，且生效了，听你的反馈改了时区就可以了

**Comment by a3311598** [comment]
> 



> > > > 目前项目可以正常使用，不过railway后台一直在打日志。不知道咋调。
> > > 
> > > 
> > > 一直打日志什么意思？我之前也用railway部署过，deploy log 一直显示不是正常的吗？
> > 
> > 
> > 这应该不是问题，但是我要看后台消息就不好看了，一直cycl

![image](https://github.com/haikerapples/timetask/assets/29724085/dee1e083-31fc-4a74-8d36-c4db8cbad472)

**Comment by swumagic** [comment]
> > > > 还有一个设置十点十分任务可以生效，设置10:10 就无法生效了。就是没有在任务列表里面
> > > 
> > > 
> > > 我的 10:10 也可以，任务添加成功，只是一直没有收到提醒
> > 
> > 
> > 10:10我这边也是可以添加成功，不过不在任务列表里面，也没生效
> 
> 我现在是可以添加成功，且在任务列表，且生效了，听你的反馈改了时区就可以了
大佬，railway部署 如何用什么命令行修改服务器的时间为北京时间？谢谢
