### ISSUE TITLE
使用最新版2.3 还是不能在企业微信上正常使用

### ISSUE THREAD

**Issue by Yanyutin753** [haikerapples/timetask#16]
[timetask] 捕获到定时任务:$time 明天 十点十分 早报
[ERROR][2023-09-04 18:51:52][chat_channel.py:274] - Worker return exception: sequence item 3: expected str instance, NoneType found
NoneType: None

**Comment by Yanyutin753** [comment]
要么就是定时Excel创建成功，文件路径为：/root/web_gpt-on-wechatapp/plugins/timetask/taskFile/timeTask.xlsx
[INFO][2023-09-04 18:53:20][wechatcomapp_channel.py:147] - [wechatcom] receive params: <Storage {'timestamp': '1693824799', 'nonce': '1694002004', 'msg_signature': '45407f49394c373ae089e832f1fbbbecf5448d4c'}>
[INFO][2023-09-04 18:53:25][wechatcomapp_channel.py:147] - [wechatcom] receive params: <Storage {'timestamp': '1693824799', 'nonce': '1694002004', 'msg_signature': '45407f49394c373ae089e832f1fbbbecf5448d4c'}>
[INFO][2023-09-04 18:53:30][wechatcomapp_channel.py:147] - [wechatcom] receive params: <Storage {'timestamp': '1693824799', 'nonce': '1694002004', 'msg_signature': '45407f49394c373ae089e832f1fbbbecf5448d4c'}>
卡住了

**Comment by haikerapples** [comment]
已修复，拉取最新的试试

**Comment by Yanyutin753** [comment]
牛牛牛，好了
