### ISSUE TITLE
设定任务出现错误：AttributeError: 'TimeTaskModel' object has no attribute 'isPerson_makeGrop'

### ISSUE THREAD

**Issue by flyinsz** [haikerapples/timetask#17]
如题，用了最新版本

**Comment by haikerapples** [comment]
具体是什么指令，发出来看下

**Comment by flyinsz** [comment]
准点报时指令：$time cron[0 * * * *] 准点报时
还有为一个群创建定时任务：$time 每天 十点十分 早报 group[男人世界🐟 🐻 🍑 📱👄🍍]

**Comment by flyinsz** [comment]
> 具体是什么指令，发出来看下

准点报时指令：$time cron[0 * * * *] 准点报时
还有为一个群创建定时任务：$time 每天 十点十分 早报 group[男人世界🐟 🐻 🍑 📱👄🍍]

**Comment by haikerapples** [comment]
重新安装一下timetask吧，应该不是代码问题，感觉是你缓存问题
