### ISSUE TITLE
报错NOT_SUPPORT_REPLYTYPE，但未在源码中找到这个异常

### ISSUE THREAD

**Issue by xieqiwen1994** [haikerapples/timetask#19]
【当前时间】：2023-09-22 14:04:00
【任务编号】：W5_6DYGA
【任务详情】：搜索周杰伦是谁), receiver=@c5e5a5dd35ee88a2f9c8aaa3b477ad98
[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务
😄执行定时任务:【bChF9MmM】，任务详情：cron[05 * * * *] cron[05 * * * *] GPT快递YT89277xxxxxxx
触发了定时任务：bChF9MmM , 任务详情：GPT快递YT89277xxxxx
[INFO][2023-09-22 14:05:00][link_ai_bot.py:82] - [LINKAI] query=快递YT8927718985205, app_code=CPmInElW, mode=gpt-3.5-turbo
[INFO][2023-09-22 14:05:03][link_ai_bot.py:94] - [LINKAI] reply=很抱歉，作为AI助手，我无法提供实时快递查询服务。建议您使用快递公司的官方网站或者快递查询平台来查询您的快递信息。, total_tokens=228
[INFO][2023-09-22 14:05:03][wechat_channel.py:186] - [WX] sendMsg=Reply(type=TEXT, content=很抱歉，作为AI助手，我无法提供实时快递查询服务。建议您使用快递公司的官方网站或者快递查询平台来查询您的快递信息。), receiver=@c5e5a5dd35ee88a2f9c8aaa3b477ad98
[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务
😄执行定时任务:【YI8JI5qy】，任务详情：cron[06 * * * *] cron[06 * * * *] 早报快递YT892771xxxxxx
触发了定时任务：YI8JI5qy , 任务详情：早报快递YT8927xxxx
路由插件异常！将使用原消息回复。错误信息：'timetask' object has no attribute 'NOT_SUPPORT_REPLYTYPE'
[INFO][2023-09-22 14:06:21][wechat_channel.py:186] - [WX] sendMsg=Reply(type=TEXT, content=⏰叮铃铃，定时任务时间已到啦~
【当前时间】：2023-09-22 14:06:00
【任务编号】：YI8JI5qy
【任务详情】：早报快递YT89277xxxxx), receiver=@c5e5a5dd35ee88a2f9c8aaa3b477ad98
😄执行定时任务:【JRqLaikT】，任务详情：cron[06 * * * *] cron[06 * * * *] 天气武汉天气
触发了定时任务：JRqLaikT , 任务详情：天气武汉天气
路由插件异常！将使用原消息回复。错误信息：'timetask' object has no attribute 'NOT_SUPPORT_REPLYTYPE'
[INFO][2023-09-22 14:06:42][wechat_channel.py:186] - [WX] sendMsg=Reply(type=TEXT, content=⏰叮铃铃，定时任务时间已到啦~
【当前时间】：2023-09-22 14:06:00
【任务编号】：JRqLaikT
【任务详情】：天气武汉天气), receiver=@c5e5a5dd35ee88a2f9c8aaa3b477ad98

**Comment by haikerapples** [comment]
看日志，由于你的 消息内容 “ 天气武汉天气 ”， 命中了 config.json配置的 拓展功能，所以本次消息会帮忙将 消息路由转发到 你项目中配置的其他插件查询一遍，如果其他插件可以正常查询到内容，此时就会将内容呈现在定时任务中。

“ NOT_SUPPORT_REPLYTYPE” 是 其他插件，在查询你的 消息体“天气武汉天气” 报的错，所以和timetask没什么关系，也就不会在timetask源码中查到此错误； timetask会使用使用原文方式，将 “天气武汉天气” 内容发送到定时任务中。

这里你得看下其他插件在消费 “天气武汉天气”指令时，为什么报错了。

**Comment by haikerapples** [comment]
看了一下NOT_SUPPORT_REPLYTYPE， 是在cow源码中有有定义，这里我看看在timetask中，如何兼容一下

**Comment by haikerapples** [comment]
已优化
