### ISSUE TITLE
格式限得有点死

### ISSUE THREAD

**Issue by astorm-z** [haikerapples/timetask#2]
很强~

不过用起来不是很方便，格式限制的比较死。能否中间多一层gpt转换，比如这样：

用户输入：“提醒我15点喝茶”

gpt转换出三个参数：
周期：今天
时间：15:00

类似这样：
![image](https://github.com/haikerapples/timetask/assets/13718643/944475a5-ef69-428c-a348-80231e54a84e)

之所以这样是因为现在插件越来越冷，每个插件都有独特的格式，老实说很容易就忘记某个插件要什么格式来输入

**Comment by haikerapples** [comment]
是的， 格式是有要求的，这样才能保证用户设定目标的准确性；

使用任何的GPT都会有准确率的问题，对于当前的插件来说，制定任务的格式不会有太高的成本，另外在任务#help 以及 查询任务中，都附带了指令格式，参考或copy即可。
