### ISSUE TITLE
时间错误

### ISSUE THREAD

**Issue by AguaC1** [haikerapples/timetask#20]
需要选择更改时区

**Comment by haikerapples** [comment]
使用的本机电脑的时间；可以设置一下电脑的时间为中国地区的时间

**Comment by AguaC1** [comment]
挂载在服务器里面的 docker部署的

**Comment by AguaC1** [comment]
日期时间是没错的嘞

**Comment by AguaC1** [comment]
![image](https://github.com/haikerapples/timetask/assets/138702017/bd18c395-7a77-48da-a00b-cff040d5aba7)

**Comment by haikerapples** [comment]
<img width="990" alt="image" src="https://github.com/haikerapples/timetask/assets/27751726/694a0825-99f7-4897-bf24-48fa211b4a18">
改下服务器的时区，之前有同学也有遇到，修改就好了

**Comment by kokojacket** [comment]
请问如何在命令行修改时区
