### ISSUE TITLE
 Failed to import plugin timetask: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by 19373842811** [haikerapples/timetask#4]
发现一个问题，python3.9以下的版本在扫描插件的时候会报错[ERROR][plugin_manager.py:91] - Failed to import plugin timetask: 'type' object is not subscriptable

**Comment by 19373842811** [comment]
原因是python3.9以下的版本不支持索引类型提示语法，解决办法有三种，要么是升级python版本；要么把TimeTaskTool.py文件中第86行的list改成List；第三就是移除类型

**Comment by haikerapples** [comment]
目前已移除
