### ISSUE TITLE
railway部署,用什么命令行修改railway服务器的时区，谢谢

### ISSUE THREAD

**Issue by swumagic** [haikerapples/timetask#51]
railway部署,用什么命令行修改railway服务器的时区，谢谢

**Comment by i2Echo** [comment]
#53 我加了一个时区偏移的配置，timezone_offset，你可以看下railway的服务器所在时区，然后对应配置这个就行了

**Comment by swumagic** [comment]
我在-8区，直接在配置文件设置加一个，timezone_offset=-8就行吗？谢谢

**Comment by i2Echo** [comment]
配置你看我这个 [pr](https://github.com/haikerapples/timetask/pull/53) 说明嘛，不过源仓库作者还没合并，你得用我那份代码配置才会生效

**Comment by swumagic** [comment]
谢谢

**Comment by swumagic** [comment]
可以执行任务了，但新问题BUG又来了。
比如我设置了 在1个微信群且发同样一个 早报 定时的指令，除了今天+事件不会触发，只要加上每天/工作日/每周几+事件，到时间群会发出一样的6-7个一样的早报图片（debug显示1分钟60S内会不断触发约6-7次同样早报插件发出图片）。（正常是一个群只有一个早报图片，感觉那里串代码BUG了），能否指教下如何修改？

大佬，你上面改了服务区时区的6个文件代码我测试也会出现我上面的的重复发图片 BUG？谢谢

**Comment by swumagic** [comment]
如下DEBUG，我看了下它会在当前分钟的60S内触发7次早报回复。不知道还需要修改哪里？我用了ChatGPT修改如下提示，还是不行。

ChatGPT修改如下，不行
在上述代码中，根据你的描述，你想要避免重复触发两次早报指令。为了实现这一点，你可以在执行早报任务时，设置一个标记来表示已经执行过早报任务。然后在下一次定时任务执行之前，先检查这个标记，如果已经执行过早报任务，则跳过执行。

在你的代码中，可以在执行早报任务时，设置一个标记变量，比如hasExecutedMorningReport，当执行早报任务时，将这个标记设置为True。在下一次定时任务执行之前，先检查这个标记，如果hasExecutedMorningReport为True，则不再触发早报任务。

下面是一个示例修改的代码片段：
python
  if self.timeTasks is not None and len(self.timeTasks) > 0:
        model: TimeTaskModel = self.timeTasks[0]
        temp_isRelogin = robot_user_id != model.toUser_id
        if model.task_type == "morning_report" and not self.hasExecutedMorningReport:
            # 执行早报任务
            self.executeMorningReportTask()
            self.hasExecutedMorningReport = True
在这个示例中，我们添加了一个hasExecutedMorningReport标记来表示是否已经执行过早报任务。当执行早报任务时，会检查这个标记，如果未执行过早报任务，则执行早报任务并将标记设置为True。在下一次定时任务执行之前，会先检查这个标记，如果已经执行过早报任务，则跳过执行。




DEBUG后台记录如下:

context: Context(type=TEXT, content=$time 每天 04:30 早报 group[ai测试群], kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x7fe03ed655d0>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@47355317142', 'receiver': '@47355317142'})

Mar 26 04:28:12
f880394f
[INFO][2024-03-25 20:28:12][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[]

Mar 26 04:28:12
f880394f
恭喜你，⏰定时任务已创建成功🎉~

Mar 26 04:28:12
f880394f
【任务编号】：HKIapvb6

Mar 26 04:28:12
f880394f
【任务详情】：每天 04:30 早报 group[ai测试群]

Mar 26 04:28:12
f880394f
【温馨提示】

Mar 26 04:28:12
f880394f
👉取消任务：$time 取消任务 任务编号

Mar 26 04:28:12
f880394f
👉任务列表：$time 任务列表

Mar 26 04:28:12
f880394f
👉更多功能：#help timetask

Mar 26 04:28:12
f880394f
[]), receiver=@47355317142

Mar 26 04:28:12
f880394f
[DEBUG][2024-03-25 20:28:12][chat_channel.py:300] - Worker return success, session_id = @47355317142da72e55f821d65f6f28ab

Mar 26 04:30:01
f880394f
[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务

Mar 26 04:30:01
f880394f
😄执行定时任务:【HKIapvb6】，任务详情：每天 04:30:00 早报 group[ai测试群]

Mar 26 04:30:01
f880394f
触发了定时任务：HKIapvb6 , 任务详情：早报

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][godcmd.py:220] - [Godcmd] on_handle_context. content: 早报

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][plugin_manager.py:189] - Plugin APILOT triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:01
f880394f
[DEBUG][2024-03-25 20:30:01][Apilot.py:51] - [Apilot] on_handle_context. content: 早报

Mar 26 04:30:02
f880394f
[DEBUG][2024-03-25 20:30:02][plugin_manager.py:194] - Plugin APILOT breaked event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:02
f880394f
[DEBUG][2024-03-25 20:30:02][wechat_channel.py:223] - [WX] start download image, img_url=https://file.alapi.

Mar 26 04:30:04
f880394f
[INFO][2024-03-25 20:30:04][wechat_channel.py:230] - [WX] download image success, size=664832, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:30:06
f880394f
[INFO][2024-03-25 20:30:06][wechat_channel.py:233] - [WX] sendImage url=https://file.alapi.cn/60s/202403261711385768.png, receiver=@@42acd7d0043e

Mar 26 04:30:11
f880394f
[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务

Mar 26 04:30:11
f880394f
😄执行定时任务:【HKIapvb6】，任务详情：每天 04:30:00 早报 group[ai测试群]

Mar 26 04:30:11
f880394f
触发了定时任务：HKIapvb6 , 任务详情：早报

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][godcmd.py:220] - [Godcmd] on_handle_context. content: 早报

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][plugin_manager.py:189] - Plugin APILOT triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:11
f880394f
[DEBUG][2024-03-25 20:30:11][Apilot.py:51] - [Apilot] on_handle_context. content: 早报

Mar 26 04:30:12
f880394f
[DEBUG][2024-03-25 20:30:12][plugin_manager.py:194] - Plugin APILOT breaked event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:12
f880394f
[DEBUG][2024-03-25 20:30:12][wechat_channel.py:223] - [WX] start download image, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:30:14
f880394f
[INFO][2024-03-25 20:30:14][wechat_channel.py:230] - [WX] download image success, size=664832, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:30:15
f880394f
[INFO][2024-03-25 20:30:15][wechat_channel.py:233] - [WX] sendImage url=https://file.alapi.cn/60s/202403261711385768.png, receiver=@@42acd7d0043e

Mar 26 04:30:20
f880394f
[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务

Mar 26 04:30:20
f880394f
😄执行定时任务:【HKIapvb6】，任务详情：每天 04:30:00 早报 group[ai测试群]

Mar 26 04:30:21
f880394f
触发了定时任务：HKIapvb6 , 任务详情：早报

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][godcmd.py:220] - [Godcmd] on_handle_context. content: 早报

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:189] - Plugin APILOT triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][Apilot.py:51] - [Apilot] on_handle_context. content: 早报

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][plugin_manager.py:194] - Plugin APILOT breaked event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:21
f880394f
[DEBUG][2024-03-25 20:30:21][wechat_channel.py:223] - [WX] start download image, img_url=https://file.alapi.c

[INFO][2024-03-25 20:30:23][wechat_channel.py:230] - [WX] download image success, size=664832, img_url=https://file.alapi.cn/60s/202403261711385768.png

[INFO][2024-03-25 20:30:25][wechat_channel.py:233] - [WX] sendImage url=https://file.alapi.cn/60s/202403261711385768.png, receiver=@@42acd7d0043e

[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务

😄执行定时任务:【HKIapvb6】，任务详情：每天 04:30:00 早报 group[ai测试群]

触发了定时任务：HKIapvb6 , 任务详情：早报

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][godcmd.py:220] - [Godcmd] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][keyword.py:52] - [keyword] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][keyword.py:52] - [keyword] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][tool.py:67] - [tool] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][tool.py:67] - [tool] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:30][plugin_manager.py:189] - Plugin APILOT triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:30][Apilot.py:51] - [Apilot] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:31][plugin_manager.py:194] - Plugin APILOT breaked event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:31][wechat_channel.py:223] - [WX] start download image, img_url=https://file.alapi.cn/60s/202403261711385768.png

[INFO][2024-03-25 20:30:32][wechat_channel.py:230] - [WX] download image success, size=664832, img_url=https://file.alapi.cn/60s/202403261711385768.png

[INFO][2024-03-25 20:30:34][wechat_channel.py:233] - [WX] sendImage url=https://file.alapi.cn/60s/202403261711385768.png, receiver=@@42acd7d0043e

[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务

😄执行定时任务:【HKIapvb6】，任务详情：每天 04:30:00 早报 group[ai测试群]

触发了定时任务：HKIapvb6 , 任务详情：早报

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][godcmd.py:220] - [Godcmd] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][keyword.py:52] - [keyword] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][keyword.py:52] - [keyword] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][tool.py:67] - [tool] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][tool.py:67] - [tool] on_handle_context. content: 早报

[DEBUG][2024-03-25 20:30:39][plugin_manager.py:189] - Plugin APILOT triggered by event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-25 20:30:39][Apilot.py:51] - [Apilot] on_handle_context. content: 早报

Mar 26 04:30:40
f880394f
[DEBUG][2024-03-25 20:30:40][plugin_manager.py:194] - Plugin APILOT breaked event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:40
f880394f
[DEBUG][2024-03-25 20:30:40][wechat_channel.py:223] - [WX] start download image, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:30:41
f880394f
[INFO][2024-03-25 20:30:41][wechat_channel.py:230] - [WX] download image success, size=664832, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:30:43
f880394f
[INFO][2024-03-25 20:30:43][wechat_channel.py:233] - [WX] sendImage url=https://file.alapi.cn/60s/202403261711385768.png, receiver=@@42acd7d0043e

Mar 26 04:30:48
f880394f
[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务

Mar 26 04:30:48
f880394f
😄执行定时任务:【HKIapvb6】，任务详情：每天 04:30:00 早报 group[ai测试群]

Mar 26 04:30:48
f880394f
触发了定时任务：HKIapvb6 , 任务详情：早报

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][godcmd.py:220] - [Godcmd] on_handle_context. content: 早报

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][plugin_manager.py:189] - Plugin APILOT triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:48
f880394f
[DEBUG][2024-03-25 20:30:48][Apilot.py:51] - [Apilot] on_handle_context. content: 早报

Mar 26 04:30:49
f880394f
[DEBUG][2024-03-25 20:30:49][plugin_manager.py:194] - Plugin APILOT breaked event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:49
f880394f
[DEBUG][2024-03-25 20:30:49][wechat_channel.py:223] - [WX] start download image, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:30:51
f880394f
[INFO][2024-03-25 20:30:51][wechat_channel.py:230] - [WX] download image success, size=664832, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:30:52
f880394f
[INFO][2024-03-25 20:30:52][wechat_channel.py:233] - [WX] sendImage url=https://file.alapi.cn/60s/202403261711385768.png, receiver=@@42acd7d0043e

Mar 26 04:30:57
f880394f
[timetask][定时检测]：当前时刻 - 存在定时任务, 执行消费 当前时刻任务

Mar 26 04:30:57
f880394f
😄执行定时任务:【HKIapvb6】，任务详情：每天 04:30:00 早报 group[ai测试群]

Mar 26 04:30:57
f880394f
触发了定时任务：HKIapvb6 , 任务详情：早报

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][godcmd.py:220] - [Godcmd] on_handle_context. content: 早报

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][keyword.py:52] - [keyword] on_handle_context. content: 早报

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin REPLICATE triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin TOOL triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][tool.py:67] - [tool] on_handle_context. content: 早报

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][plugin_manager.py:189] - Plugin APILOT triggered by event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:57
f880394f
[DEBUG][2024-03-25 20:30:57][Apilot.py:51] - [Apilot] on_handle_context. content: 早报

Mar 26 04:30:58
f880394f
[DEBUG][2024-03-25 20:30:58][plugin_manager.py:194] - Plugin APILOT breaked event Event.ON_HANDLE_CONTEXT

Mar 26 04:30:58
f880394f
[DEBUG][2024-03-25 20:30:58][wechat_channel.py:223] - [WX] start download image, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:31:00
f880394f
[INFO][2024-03-25 20:31:00][wechat_channel.py:230] - [WX] download image success, size=664832, img_url=https://file.alapi.cn/60s/202403261711385768.png

Mar 26 04:31:01
f880394f
[INFO][2024-03-25 20:31:01][wechat_channel.py:233] - [WX] sendImage url=https://file.alapi.cn/60s/202403261

**Comment by i2Echo** [comment]
感觉可能是别的插件的问题，建议先只用定时任务插件排查原因（只设置最简单的文字提醒）

**Comment by swumagic** [comment]
> 感觉可能是别的插件的问题，建议先只用定时任务插件排查原因（只设置最简单的文字提醒）

试了不行，另外大佬我用你的PR原代码没修改，同样会出现错误，任务列表一开始是有待执行任务。过了时间没有待执行的任务。也没有任何输出。微信也没有任何反应。你这边不修改我截图里的那2段代码，能输出和微信显示结果吗？


我看了下debug除了今天+事件不会触发，只要加上每天/工作日/每周几+事件，到时间群会发出一样的6-7个一样的早报图片（debug显示1分钟60S内会不断触发约6-7次同样早报插件发出图片）。每天+等多日发的指令 逻辑应该有问题，就没找到修改的地方

**Comment by swumagic** [comment]
根据你的描述，如果robot_user_id和model.toUser_id一定是相同的，那么在第二段代码中会进入死循环，因为temp_isRelogin始终为False，不会执行重新登录的逻辑。

为了解决这个问题，你可以考虑修改第二段代码中的判断条件，不再比较robot_user_id和model.toUser_id是否相同，而是直接判断任务列表是否为空。如果任务列表不为空，则表示有任务需要处理，可以执行重新登录的逻辑。修改后的代码如下：

python
# 取出任务中的一个模型
if self.timeTasks is not None and len(self.timeTasks) > 0:
    # 更新为重新登录态
    self.isRelogin = True
    # 等待登录完成
    time.sleep(3)
    # 更新userId
    ExcelTool().update_userId()
    # 刷新数据
    self.refreshDataFromExcel()
    # 更新为非重新登录态
    self.isRelogin = False
这样修改后，无论robot_user_id和model.toUser_id是否相同，只要任务列表不为空，就会执行重新登录的逻辑。这样可以避免进入死循环的问题。

**Comment by i2Echo** [comment]
我这边不管是本地还是服务器部署都正常执行，你尽量控制变量法排除其他因素，因为我也不知道你什么坏境用了哪些插件

**Comment by swumagic** [comment]
谢谢你的PR，我在检查下看，目前主要每天指令有bug重复发多个早报图片,

**Comment by maomaogreen** [comment]
> 谢谢你的PR，我在检查下看，目前主要每天指令有bug重复发多个早报图片,

有同样的问题，不知道是不是和docker部署有关？求解决
