### ISSUE TITLE
设定好的每天任务，只生效了一次，后续不生效了，任务表里的任务还在。

### ISSUE THREAD

**Issue by scholarli** [haikerapples/timetask#6]
设定好的每天任务，只生效了一次，后续不生效了，任务表里的任务还在。

**Comment by ymeimei** [comment]
+1 早报设定的每天，只生效了一次

**Comment by haikerapples** [comment]
已修复，可以更新最新版的2.1试试

**Comment by scholarli** [comment]
连续两天有，到第三天又失效了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haikerapples/timetask"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月23日(星期天) 凌晨0:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haikerapples/timetask] 设定好的每天任务，只生效了一次，后续不生效了，任务表里的任务还在。 (Issue #6)





 
Closed #6 as completed.

**Comment by flyinsz** [comment]
+1，同样的问题。设定了报时任务，到23点后就自动不执行了

**Comment by swumagic** [comment]
> 使用最新版2.6试试

目前有新BUG ，比如我设置了 在3个微信群且在不同时间段发同样一个 早报定时的指令，到时间每个群会发出一样的3个早报图片。（正常是一个群只有早报图片，感觉那里串代码BUG了），谢谢作者大大
