### ISSUE TITLE
群聊定时任务，重启后就会失效

### ISSUE THREAD

**Issue by joyce677** [haikerapples/timetask#7]
私聊的定时任务重启后还在，但是群聊里设置的定时任务就会失效了。

**Comment by haikerapples** [comment]
群聊名称有变化么？ 可以使用最新版试试

**Comment by Francis776** [comment]
> 群聊名称有变化么？ 可以使用最新版试试

更新后可以用了。
如果插件带回复图片的功能，timetask定时后无法完成图片回复。

**Comment by haikerapples** [comment]
问题描述的不是很清楚， 是不是如下的意思：

设置了一个定时任务A，A是一个会路由给其他插件的定时任务； 在A执行时，会将消息路由给其他插件Plugin，然后其他的Plugin 返回了一个图片内容，此时定时插件无法发图片内容？

**Comment by Francis776** [comment]
> 问题描述的不是很清楚， 是不是如下的意思：
> 
> 设置了一个定时任务A，A是一个会路由给其他插件的定时任务； 在A执行时，会将消息路由给其他插件Plugin，然后其他的Plugin 返回了一个图片内容，此时定时插件无法发图片内容？

对，是的，试过几个返图的插件，如keyword，设置了一个关键词=图片的链接，单独执行keyword能成功返回图片，但是让timetask去定时执行这个关键词，那么他返回的不是图片，而是发送的这个图片的链接。如果是其他插件，只要是文字内容定时插件都能正常返回，但是图片内容就会报错。

**Comment by haikerapples** [comment]
优化了一下，拉下最新的代码试试

**Comment by Francis776** [comment]
> 优化了一下，拉下最新的代码试试

问题解决，👍
